import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';

import {
  createInstance
} from "@optimizely/optimizely-sdk";

const optimizelyClient = createInstance({
  sdkKey: 'CPCdyJVM8Xe4sBDNjot53',
})

export default function Home() {

  const userId = uuidv4();

  // Example Of Sending An Event
  const onClick = () => {
    console.log("click");
    optimizelyUserContext.trackEvent('viewedpage');
  }

  const optimizelyUserContext = optimizelyClient.createUserContext(
    userId,
    // Example of passing attributes
    {
      location: "london",
      devicetype: "ios"
    }
  );

  const [isFeatureEnabled, renderIsFeatureEnabled] = useState(true);

  useEffect(() => {
    // Query One Flag
    const featureFlagTargetedDelivery = optimizelyUserContext.decide('feature_flag');
    console.log('featureFlagTargetedDelivery', featureFlagTargetedDelivery.enabled);

    renderIsFeatureEnabled(featureFlagTargetedDelivery.enabled);

    // Query All Flags
    const allDecisions = optimizelyUserContext.decideAll();
    console.log('allDecisions', allDecisions);

    Object.entries(allDecisions).map(([flagKey, decision], index) => {
      console.log(`Key=${flagKey};Rule ${decision.ruleKey};Enabled=${decision.enabled}`);
    });
  }, [optimizelyUserContext]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className={styles.main}>

        <h3 className={styles.title}>
          Is Feature Flag Enabled: {isFeatureEnabled.toString()}
        </h3>

        <button onClick={onClick} className={styles.grid}>
          Generated Event
        </button>

        <div>
        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
